### ISSUE TITLE
Yazılım önerme sayfası için bir kaç düşünce

### ISSUE THREAD

**Issue by sabriunal** [pardus/pardus-software#8]
Lisans kutusu altında Telif Hakkı Metni kutusunun işlevini anlamadım. Lisans metninin ingilizcesini veya Türkçesini mi yapıştırmak gerekiyor. Veya açıklamaların lisansından mı bahsediliyor çözemedim. Belki o kısma bir açıklama eklenebilir.

Adınız kısmı "Adınız Soyadınız" olsa daha makul olabilir. Neden saedce adın talep edildiği de belirsiz. İletişim içinse Ad ve Soyad birlikte talep edilmesi daha doğru olabilir.

"Uygulama Pardus depolarında mevcut mu?" metni önünde bir checkbox bulunuyor. Soru ile checkbox hafifce uyumsuz duruyor. Belki "Uygulama Pardus depolarında mevcut mu?" sorusunu sola alıp checkbox'ı sağa alıp checkbox ve evet şeklinde uyarlanabilir. 

Bir de uygulamanın hakkında sayfasında kaynak kodlarına veya bu sayfaya giden bir link bulamadım. Web Sitesi linki doğal olarak pardus.org.tr'yi açıyor.

**Comment by fthaltun** [comment]
Thanks, I tried to fix it as much as possible. We may edit this page in more detail in the future.
